FROM alpine:3.8
RUN apk --no-cache add \
    python3 \
    py3-pillow \
    py3-magic \
    py3-requests \
    && mkdir /cert

# Run requires certs mapped to /cert, script in /, calibration profiles in /calibration
ADD calibration /calibration
ADD instaxify_service.py /

ENTRYPOINT ["python3"]
CMD ["/instaxify_service.py"]
