FROM registry.xe2/debian:stretch-slim

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y \
    python3 \
    python3-requests \
    python3-magic \
    python3-pillow \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /cert

# Run requires certs mapped to /cert, script in /, calibration profiles in /calibration
ADD calibration /calibration
ADD instaxify_service.py /

# Doesn't print out access messages  (stdout?)
#ENTRYPOINT ["python3"]
#CMD ["/instaxify_service.py"]

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["python3 /instaxify_service.py"]
